version: '3.9'

services:
  dto:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports: 
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes: 
  db: